- id: kustomize-validate
  name: check that kustomize can build successfully
  description: validates that broken kustomize files won't be committed
  entry: hooks/kustomize-validate.sh
  language: script
  files: kustomization\.yaml$
