name: semantic-release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  semantic-release:
    uses: clickdealer/github-actions/.github/workflows/semantic-release.yaml@v1
    secrets: inherit
